astarte-platform/astarte-device-sdk-esp32

- CHANGELOG.md
- astarte_pairing.c
> astarte_pairing: do not try to print a NULL json_error

- CHANGELOG.md
> Prepare 0.11.0-rc.0 release

- astarte_device.c
Also, notify the reinit_task instead of directly deleting it, so that it doesn't
die in the middle of a call
> astarte_device: free all resources after a failure

- CHANGELOG.md
Add 0.11.0-rc.1 release date to changelog file.
> Prepare v0.11.0-rc.1

- CHANGELOG.md
- astarte_device.c
- include/astarte_device.h
Return the connected status of the device
> astarte_device: add astarte_device_is_connected

- astarte_device.c
> astarte_device: fix astarte_device_stream_aggregate

- CHANGELOG.md
- astarte_device.c
- include/astarte_device.h
> astarte_device: add astarte_device_unset_path function

- CHANGELOG.md
- CMakeLists.txt
- astarte_device.c
- examples/toggle_led/CMakeLists.txt
- examples/toggle_led/main/CMakeLists.txt
> Add support for esp-idf 4.0 build system

- CHANGELOG.md
- include/astarte.h
> astarte.h: add ASTARTE_SDK_VERSION

- CHANGELOG.md
Update changelog file.
Signed-off-by: Davide Bettio <davide.bettio@ispirata.com>
> Prepare 0.11.1 release

- CHANGELOG.md
- astarte_device.c
> Fix bug in device reinitialization

- CHANGELOG.md
Update version number and fix mistake in CHANGELOG.md file.
> Bump version number

- CHANGELOG.md
- include/astarte.h
Update CHANGELOG.md and bump include/astarte.h.
> Prepare v0.11.4 release

- CHANGELOG.md
Add release date to CHANGELOG.md.
> Prepare v1.0.0-beta.1

- CHANGELOG.md
- astarte_device.c
- include/astarte_device.h
Allow temporarily suspending the MQTT client
Fix #51
> astarte_device: add astarte_device_stop function

- .github/workflows/docs-workflow.yaml
- .gitignore
- README.md
- doc/astarte-device-sdk-esp32.doxy
- doc/docmain.dox
- examples/toggle_led/README.md
Enhance READMEs and upload generated Doxygen documentation to Astarte docs
> Readme and doc revamp

- .github/workflows/docs-workflow.yaml
> doc-workflow: put device-sdks docs under the main Astarte versioning

- README.md
> README: fix documentation link

- astarte_credentials.c
- astarte_device.c
- astarte_pairing.c
Decrease some prints from info to debug to avoid spammines and/or printing
sensitive information in logs.
> Rework log levels

- CHANGELOG.md
- include/astarte.h
> Prepare 1.0.1 release

- astarte_device.c
Change the introspection string generation in `send_introspection` from a static value of 512 characters to a dynamic one calculated upon the items located in `interfaces_list`. This prevents a sudden block on introspection publication over a value that could be perceived as too arbitrary.
Add a warning, though, if the size is greater than 4KiB.
close #82 
Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>
> Dynamic introspection size

- CHANGELOG.md
- doc/docmain.dox
- include/astarte.h
Just bump version number, and add release date.
> Prepare 1.0.3

- astarte_bson.c
> Fix BSON parsing of arrays

- CHANGELOG.md
- doc/docmain.dox
- include/astarte.h
Just bump the version number, and add the release date.
> Prepare 1.1.0

- CHANGELOG.md
- astarte_hwid.c
> Fix hwid generation

- README.md
> Add RTOS usage in readme

- include/astarte_bson_serializer.h
- src/astarte_bson_serializer.c
> Add checks over optional parametes in bson serializer

- CHANGELOG.md
- Kconfig
- src/astarte_pairing.c
> Configurable limit on jwt size

- .clang-tidy
- include/astarte_bson_serializer.h
- include/uuid.h
- src/astarte_bson.c
- src/astarte_bson_serializer.c
- src/astarte_credentials.c
- src/astarte_device.c
- src/uuid.c
> Fix readability identifier length

- CHANGELOG.md
- CMakeLists.txt
- README.md
- examples/aggregates/main/src/example_task.c
- examples/datastreams/main/src/example_task.c
- examples/toggle_led/main/src/example_task.c
- include/astarte_bson.h
- include/astarte_bson_deserializer.h
- include/astarte_device.h
- src/astarte_bson.c
- src/astarte_bson_deserializer.c
- src/astarte_device.c
- tests/common/CMakeLists.txt
- tests/common/test_astarte_bson_deserializer.c
- tests/common/test_astarte_bson_deserializer.h
- tests/host_app/main/test_runner.c
- tests/target_app/main/test_runner.c
Improve the usability of the bson deserializer.
Closes #108
> Improve astarte bson deserializer

- .clang-tidy
- CHANGELOG.md
- include/astarte.h
- include/astarte_bson_serializer.h
- include/astarte_credentials.h
- include/astarte_list.h
- include/astarte_pairing.h
- src/astarte_bson_serializer.c
Also deprecated all the re-introduced functions/structures.
> Reverted breaking changes 

- examples/aggregates/main/src/example_task.c
- include/astarte_bson_serializer.h
- include/uuid.h
- src/astarte_bson_serializer.c
- src/astarte_device.c
- src/uuid.c
- tests/common/test_astarte_bson_serializer.c
- tests/host/test_uuid.c
Revert some breaking changes that have been postponed.
See issue: #161, #162.
> Revert postponed changes

- idf_component.yml
run `compote component upload --namespace astarte-platform --name astarte-device-sdk-esp32`.
Closes #165
> Prepare for component publish on ESP-Registry

- .gitignore
> Add dependencies.lock to the gitignore

- include/astarte_bson_deserializer.h
- include/astarte_bson_serializer.h
> Document optional BSON arguments

- CHANGELOG.md
- include/astarte_hwid.h
- include/uuid.h
- src/astarte_device.c
- src/astarte_hwid.c
- src/uuid.c
> Hwid functions return values

- CHANGELOG.md
- examples/datastreams/main/src/example_task.c
- include/astarte_device.h
- src/astarte_device.c
> Add user data to callback functions

- CHANGELOG.md
- CMakeLists.txt
- include/astarte.h
- src/astarte_err_to_name.c
> astarte_err_to_name implementation
