astarte-platform/astarte-device-sdk-esp32

astarte_pairing.c
=> astarte_pairing: close nvs after we're done with it

CHANGELOG.md, astarte_credentials.c
=> astarte_credentials: use ECDSA keys instead of RSA keys

CHANGELOG.md, astarte_credentials.c, astarte_device.c, astarte_pairing.c, include/astarte_credentials.h, include/astarte_device.h, include/astarte_pairing.h
Allow the user to pass an explicit credentials secret to the device, or to manipulate the NVS to get/set/delete the credentials secret.
Fix #14
=> Add more flexibility for credentials secret

astarte_device.c
This reduces memory usage by reducing overlap between previously
allocated resources and new resources
=> astarte_device: free resources earlier in init_connection

astarte_credentials.c
=> astarte_credentials: always close nvs when we're done with it

CHANGELOG.md, astarte_device.c, include/astarte_device.h
Allow sending data to object aggregated interfaces
=> astarte_device: add astarte_device_stream_aggregate

CHANGELOG.md, astarte_bson_serializer.c
It was using 64 bits instead of 32 in astarte_bson_serializer_append_document
=> astarte_bson_serializer: fix little endian to host conversion

CHANGELOG.md, Kconfig, astarte_hwid.c
This is the new default behaviour, but can be toggled from make menuconfig if
the user wants to keep using an hardware ID generated with the old behaviour.
See https://github.com/astarte-platform/astarte/issues/277
=> astarte_hwid: allow using UUIDv5 to derive the hardware ID

CHANGELOG.md, astarte_credentials.c, astarte_device.c, astarte_hwid.c, astarte_pairing.c, include/astarte.h
Rather than always returning ASTARTE_ERR, put together a more meaningful error structure and ensure we return it consistently.
=> Improve error management

astarte_pairing.c
If esp-idf version is at least 4.0.0, set buffer_size_tx within
http_config structure.
=> Fix http_config if esp-idf version is at least 4.0.0

astarte_device.c, include/astarte_device.h
Allow sending explicit timestamps to mappings that support them.
=> Add astarte_device_stream_*_with_timestamp functions

examples/toggle_led/CMakeLists.txt
Fix build error with cmake esp-idf (esp-idf >= 4.0).
=> toggle_button example: fix relative path in CMakeLists.txt

CHANGELOG.md, astarte_device.c, examples/toggle_led/main/app_main.c, include/astarte_device.h
Allow the caller to be notified when the device connects or disconnects.
Fix #50
=> astarte_device: add user connection/disconnection callbacks

CHANGELOG.md, astarte_device.c, examples/toggle_led/main/app_main.c, include/astarte_device.h
Allow failures to be propagated to the caller
Fix #55
=> astarte_device: return astarte_err_t from astarte_device_start

examples/toggle_led/main/app_main.c
This was missed when the whole codebase was reformatted
=> app_main: run clang-format

CHANGELOG.md, astarte_device.c, examples/toggle_led/main/app_main.c, include/astarte_device.h, include/astarte_interface.h, include/astarte_list.h
Pass a pointer to an `astarte_interface_t` struct. This allows to cleanup subscriptions, subscribing only to server owned interfaces (see https://github.com/astarte-platform/astarte/issues/568).
=> Change astarte_device_add_interface API

CHANGELOG.md, astarte_device.c, include/astarte_device.h
Allow passing an explicit realm to **astarte_device_config_t.**
Signed-off-by: Antonio Gisondi <antonio.gisondi@secomind.com>
=> Config realm at runtime

CHANGELOG.md, include/uuid.h, uuid.c
Add uuid_generate_v4 function.
Generate a random UUIDv4 using esp_fill_random function that makes use of hardware random number generator.
See [esp_fill_random](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/random.html#_CPPv415esp_fill_randomPv6size_t).
Signed-off-by: Antonio Gisondi <antonio.gisondi@secomind.com>
=> Add uuid_generate_v4 function

CHANGELOG.md, astarte_bson_serializer.c, astarte_device.c, include/astarte_bson_serializer.h, include/astarte_bson_types.h, include/astarte_device.h
Add `astarte_bson_serializer_append_<T>_array` functions to BSON serializer and
`astarte_device_stream_<T>_array(_with_timestamp)` functions to astarte_device (for each supported
type) in order to enable sending arrays to array typed datastreams.
=> Add support to arrays for datastreams

CHANGELOG.md, astarte_device.c, include/astarte_device.h
Three possible ways were found to implement the previously unsupported feature of unsetting a property belonging to a server-owned interface.
The first was to send an `astarte_device_data_event_t` with a `NULL` `bson_data` to the `data_event_callback`.
Similarly, a possibility was to send to it an `astarte_device_data_event_t` with the `bson_type` set as a newly introduced `BSON_TYPE_NULL`.
Lastly, it was considered the introduction of a new optional  `astarte_device_data_event_callback_t` called `unset_data_event_callback` in charge of handling only unset property operations.
The first two cases were deemed unsafe as the new behavior could cause troubles to users that already employ the SDK and have defined a `device_data_event_callback_t` without checking the two fields.
The latter was …
=> Add support to server-owned property unset

CHANGELOG.md, astarte_device.c, include/astarte_device.h
const qualifier was missing by mistake, add it to all string functions.
=> Add const qualifiers for all `char *` used with string types

CHANGELOG.md, astarte_device.c, include/astarte.h
Avoid adding an interface with major and minor version numbers at zero adding a check to return a specific error.
Close #94 
Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>
=> Avoid adding invalid interface

CHANGELOG.md, astarte_device.c
The MQTT library sets a clean session by default, so the device starts with a clean session every time, to change this behavior it is necessary to enable disable_clean_session.
Before enable it pay attention if the [#issue-29](https://github.com/astarte-platform/astarte-device-sdk-esp32/issues/29) has been solved.
Closes #115.
=> Add Empty cache support

README.md
Add a section to the readme regarding the TLS certificates errors.
=> Document ignore tls errors

include/astarte_device.h, src/astarte_bson_serializer.c, src/astarte_device.c, src/astarte_hwid.c, src/uuid.c
Initialize local arrays of char to 0. 
They are often used as strings and some functions might assume them to be null-terminated from the start.
=> Initialize strings
